namespace LoanCalculator.Core.Pdf
{
    public class PdfGeneratorBaseWithDisclaimer : PdfGeneratorBase
    {
        protected void GenerateDisclaimerData()
        {
            DrawH1("Home Loan Calculator App Disclaimer");
            DrawH2("General Disclaimer");
            DrawParagraph("The Home Loan Calculator App (referred to as \"Home Loan Calculator Insights App\") is provided for informational purposes only. The results and information generated by the App are estimates based on the inputs provided by the user and should not be considered definitive or legally binding. The App does not provide legal, financial, or professional advice and should not be relied upon for such purposes.");

            DrawH2("No Legal Obligations");
            DrawH3("Accuracy of Information");
            DrawParagraph("The App aims to provide accurate calculations and information. However, the accuracy, completeness, and timeliness of the data provided cannot be guaranteed. The App owner (referred to as \"we\" or \"us\") makes no representations or warranties of any kind, express or implied, about the reliability, suitability, or availability of the App or the information, products, services, or related graphics contained in the App for any purpose.");

            DrawH3("No Liability");
            DrawParagraph("We will not be liable for any loss or damage, including but not limited to indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of or in connection with the use of the App. Users use the App at their own risk.");

            DrawH3("No Financial Advice");
            DrawParagraph("The App is not intended to substitute professional financial advice. The information generated by the App is based on the inputs provided by the user and should be used as a guide only. It is recommended that users consult with their financial adviser before making any financial decisions. We do not guarantee the suitability or appropriateness of any financial product or transaction described in the App.");

            DrawH3("Third-Party Links");
            DrawParagraph("The App may contain links to third-party websites or services not owned or controlled by us. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites or services. By using the App, you expressly relieve us from any liability arising from your use of any third-party website or service.");

            DrawH3("Changes to the App");
            DrawParagraph("We reserve the right to make changes to the App or discontinue any part of the App without notice at any time. We shall not be liable to users or any third party should we exercise such right.");

            DrawH2("User Responsibilities");
            DrawH3("Accuracy of Inputs");
            DrawParagraph("Users are responsible for ensuring the accuracy of the inputs they provide to the App. The results generated by the App are only as accurate as the information provided by the user.");

            DrawH3("Professional Consultation");
            DrawParagraph("Users should seek advice from a qualified financial adviser to understand the financial implications of their decisions fully. The App should not be the sole basis for making financial decisions.");

            DrawH3("Compliance with Laws");
            DrawParagraph("Users must comply with all applicable laws and regulations when using the App. We are not responsible for any illegal use of the App by users.");

            DrawH2("Conclusion");
            DrawParagraph("By using the Home Loan Calculator Insights App, you acknowledge that you have read this disclaimer, understand it, and agree to be bound by its terms and conditions. If you do not agree with any part of this disclaimer, you must not use the App.\r\nThis disclaimer is subject to change without notice. Users are recommended to review the disclaimer periodically for any updates or changes.\r\nFor any questions or concerns regarding this disclaimer, please contact us at [yoursimpleapps@gmail.com].\r\n");
        }
    }
}
