<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Syncfusion.Pdf.NET" Version="28.2.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LoanCalculator.Core\LoanCalculator.Core.csproj" />
    <ProjectReference Include="..\LoanCalculator.Models\LoanCalculator.Models.csproj" />
  </ItemGroup>

</Project>
