<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>LoanCalculatorMaui</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>LoanCalculatorMaui</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.pj.loancalcpro</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
		<DefaultLanguage>en-au</DefaultLanguage>
		<AndroidSigningKeyStore>catholicsaints.keystore</AndroidSigningKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-android|AnyCPU'">
	  <AndroidKeyStore>True</AndroidKeyStore>
	  <AndroidSigningKeyAlias>keyalias.alias</AndroidSigningKeyAlias>
	  <AndroidSigningStorePass>CatholicSaintsPassword@01</AndroidSigningStorePass>
	  <AndroidSigningKeyPass>CatholicSaintsPassword@01</AndroidSigningKeyPass>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|AnyCPU'">
	  <AndroidKeyStore>True</AndroidKeyStore>
	  <AndroidSigningKeyAlias>keyalias.alias</AndroidSigningKeyAlias>
	  <AndroidSigningStorePass>CatholicSaintsPassword@01</AndroidSigningStorePass>
	  <AndroidSigningKeyPass>CatholicSaintsPassword@01</AndroidSigningKeyPass>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#374961" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Remove="Extensions\Data\Theme.CommonDataGridStyles.xaml" />
	  <MauiXaml Remove="Extensions\Data\Theme.CommonStyles.xaml" />
	  <MauiXaml Remove="Extensions\Data\Theme.Dark.xaml" />
	  <MauiXaml Remove="Extensions\Data\Theme.Forest.xaml" />
	  <MauiXaml Remove="Extensions\Data\Theme.Light.xaml" />
	  <MauiXaml Remove="Extensions\Data\Theme.Warm.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Extensions\DisclaimerData\AppLaunchDisclaimerData.txt" />
	  <None Remove="Resources\AppIcon\appiconfg.png" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Extensions\Data\Theme.Warm.xaml">
	    <Generator></Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Include="Extensions\Data\Theme.Forest.xaml">
	    <Generator></Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Include="Extensions\Data\Theme.CommonDataGridStyles.xaml">
	    <Generator></Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Include="Extensions\Data\Theme.CommonStyles.xaml">
	    <Generator></Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Include="Extensions\Data\Theme.Dark.xaml">
	    <Generator></Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Include="Extensions\Data\Theme.Light.xaml">
	    <Generator></Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Include="Extensions\DisclaimerData\AppLaunchDisclaimerData.html" />
	  <EmbeddedResource Include="Extensions\DisclaimerData\AppLaunchDisclaimerData.txt" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="11.0.0" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.30" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.1" />
		<PackageReference Include="Plugin.InAppBilling" Version="8.0.5" />
		<PackageReference Include="Sentry.Maui" Version="5.9.0" />
		<PackageReference Include="Syncfusion.Maui.Core" Version="28.2.7" />
		<PackageReference Include="Syncfusion.Maui.Expander" Version="28.2.7" />
		<PackageReference Include="Syncfusion.Maui.Popup" Version="28.2.7" />
		<PackageReference Include="Syncfusion.Maui.ProgressBar" Version="28.2.7" />
		<PackageReference Include="Syncfusion.Maui.DataGrid" Version="28.2.7" />
		<PackageReference Include="Syncfusion.Maui.TabView" Version="28.2.7" />
		<PackageReference Include="Syncfusion.Maui.ListView" Version="28.2.7" />
		<PackageReference Include="Syncfusion.Maui.Buttons" Version="28.2.7" />
		<PackageReference Include="Syncfusion.Maui.Sliders" Version="28.2.7" />
		<PackageReference Include="Syncfusion.Maui.Inputs" Version="28.2.7" />
		<PackageReference Include="Syncfusion.Maui.Charts" Version="28.2.7" />
		<PackageReference Include="Syncfusion.Pdf.NET" Version="28.2.7" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\LoanCalculator.Core\LoanCalculator.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Controls\DisclaimerBannerView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\InsightsItemView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\InAppPurchaseView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\PopupDisclaimerView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\Colors.xaml">
	    <Generator></Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\Styles.xaml">
	    <Generator></Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\ExpenseView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\IncomeView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\LoanView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Controls\ThreeColumnBorderedContentView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="View\SettingsView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Platforms\MacCatalyst\Services\" />
	  <Folder Include="Platforms\Tizen\Services\" />
	</ItemGroup>

	<ItemGroup>
	  <MauiAsset Include="Resources\AppIcon\appiconfg.png" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Controls\InAppPurchaseView.xaml.cs">
	    <DependentUpon>PremiumBuyView.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	  
</Project>
